import json
import os
import shutil
from pathlib import Path
import pandas as pd
from datetime import datetime
import sqlite3
import numpy as np

# --- CONFIGURATION ---
OUTPUT_FOLDER = "mobile_build"  # The folder for the website

# Reuse your existing mapping logic
PROVINCE_MAPPING = {
    'SV': 'Sihanoukville', 'KK': 'Koh Kong', 'SI': 'Siem Reap', 'PV': 'Prey Veng',
    'SR': 'Svay Rieng', 'KD': 'Kandal', 'KS': 'Kampong Speu', 'KC': 'Kampong Cham',
    'KH': 'Kampong Chhnang', 'BB': 'Battambang', 'PS': 'Pursat', 'PH': 'Preah Vihear',
    'KT': 'Kampong Thom', 'PL': 'Pailin', 'BM': 'Banteay Meanchey', 'TB': 'Tboung Khmum',
    'OM': 'Oddar Meanchey', 'KP': 'Kampot', 'KE': 'Kep', 'KR': 'Kratie',
    'ST': 'Stung Treng', 'MK': 'Mondulkiri', 'RK': 'Ratanakiri', 'PP': 'Phnom Penh', 'TK': 'Takeo'
}

def get_province_full_name(abbreviation):
    return PROVINCE_MAPPING.get(abbreviation.upper(), abbreviation)

def extract_province_from_site_id(site_id):
    if isinstance(site_id, str) and len(site_id) >= 2:
        return site_id[:2].upper()
    return 'Unknown'

def generate_mobile_site():
    print("="*70)
    print("MOBILE SITE GENERATOR (ADD-ON)")
    print("="*70)
    
    scripts_folder = Path(__file__).parent.resolve()
    output_dir = scripts_folder / OUTPUT_FOLDER
    data_dir = output_dir / "site_data"
    
    # 1. Clean and recreate output folder
    if output_dir.exists():
        shutil.rmtree(output_dir)
    output_dir.mkdir()
    data_dir.mkdir()

    # 2. Find the Excel file (Generated by your MAIN script earlier)
    excel_files = list(scripts_folder.glob("installed_sites_production_*.xlsx"))
    if not excel_files:
        print("✗ No production file found. Make sure sites_table_nogui.py ran first.")
        return
    excel_file = max(excel_files, key=lambda p: p.stat().st_mtime)
    print(f"  Reading: {excel_file.name}")

    try:
        df = pd.read_excel(excel_file, sheet_name='Installed Sites Production')
    except Exception as e:
        print(f"✗ Error: {e}")
        return

    # 3. Process Data
    print(f"  Processing {len(df)} sites for mobile...")
    df['Province'] = df['Site_ID'].apply(extract_province_from_site_id)
    df['Province_Full'] = df['Province'].apply(get_province_full_name)
    
    date_cols = [col for col in df.columns if isinstance(col, str) and len(col) == 10 and col[4] == '-' and col[7] == '-']
    
    site_metadata = {}
    
    # 4. Generate Files
    for idx, row in df.iterrows():
        site_id = str(row['Site_ID'])
        array_size = row.get('Array_Size_kWp', 0)
        
        # Lightweight Metadata for the Index Page
        meta = {
            'site_id': site_id,
            'site_name': str(row.get('Site', site_id)),
            'province': row['Province_Full'],
            'array_size': array_size,
            'avg_yield': row.get('Avg_Yield_30d_kWh_kWp', 0),
            'panel': str(row.get('Panel_Description', 'N/A')),
            'project': str(row.get('Project', 'N/A'))
        }
        site_metadata[site_id] = meta
        
        # Heavy Daily Data for JSON files
        daily_data = []
        for d in date_cols:
            if pd.notna(row[d]):
                val = float(row[d])
                spec = val / float(array_size) if array_size > 0 else 0
                daily_data.append({'date': d, 'kwh': val, 'yield': spec})
        
        # Save JSON
        with open(data_dir / f"{site_id}.json", 'w') as f:
            json.dump({'meta': meta, 'history': daily_data}, f)

    # 5. Generate Index HTML
    html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Solar Mobile</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <style>
        body {{ font-family: -apple-system, sans-serif; background: #f0f2f5; margin: 0; padding-bottom: 2rem; }}
        .header {{ background: #2c3e50; color: white; padding: 1rem; position: sticky; top: 0; z-index: 100; }}
        .search-bar {{ width: 100%; padding: 10px; border-radius: 8px; border: none; margin-top: 10px; font-size: 16px; box-sizing: border-box; }}
        .site-card {{ background: white; margin: 10px; padding: 15px; border-radius: 10px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); cursor: pointer; }}
        .site-header {{ display: flex; justify-content: space-between; align-items: center; }}
        .yield-badge {{ padding: 5px 10px; border-radius: 15px; color: white; font-weight: bold; font-size: 0.9rem; }}
        .modal {{ display: none; position: fixed; top: 0; left: 0; width: 100%; height: 100%; background: white; z-index: 200; overflow-y: auto; }}
        .modal.active {{ display: block; }}
        .back-btn {{ background: none; border: none; font-size: 1.5rem; cursor: pointer; padding: 10px; }}
    </style>
</head>
<body>
    <div class="header">
        <h2 style="margin:0">Solar Fleet ({len(site_metadata)})</h2>
        <input type="text" class="search-bar" placeholder="Search site or province..." onkeyup="filterSites(this.value)">
    </div>

    <div id="site-list"></div>

    <div id="detail-modal" class="modal">
        <div style="padding: 1rem; border-bottom: 1px solid #eee; display: flex; align-items: center; gap: 10px; position: sticky; top: 0; background: white;">
            <button class="back-btn" onclick="closeModal()">←</button>
            <h3 id="detail-title" style="margin:0">Site Name</h3>
        </div>
        <div style="padding: 1rem;">
            <div id="detail-stats" style="display: grid; grid-template-columns: 1fr 1fr; gap: 10px; margin-bottom: 20px;"></div>
            <div style="height: 300px;"><canvas id="chart"></canvas></div>
            <p id="loading" style="text-align: center; color: #666;">Loading data...</p>
        </div>
    </div>

    <script>
        const sites = {json.dumps(list(site_metadata.values()))};
        let chartInstance = null;

        function renderList(list) {{
            const container = document.getElementById('site-list');
            let html = '';
            list.slice(0, 100).forEach(s => {{ // Limit render for speed
                let color = s.avg_yield > 4.5 ? '#27ae60' : (s.avg_yield > 3.5 ? '#2980b9' : '#e74c3c');
                html += `<div class="site-card" onclick="openSite('${{s.site_id}}')">
                    <div class="site-header">
                        <div>
                            <div style="font-weight:bold; font-size: 1.1rem">${{s.site_name}}</div>
                            <div style="color: #666; font-size: 0.9rem">${{s.province}} • ${{s.array_size}} kWp</div>
                        </div>
                        <div class="yield-badge" style="background:${{color}}">${{s.avg_yield.toFixed(2)}}</div>
                    </div>
                </div>`;
            }});
            container.innerHTML = html;
        }}

        function filterSites(query) {{
            const q = query.toLowerCase();
            const filtered = sites.filter(s => 
                s.site_name.toLowerCase().includes(q) || 
                s.site_id.toLowerCase().includes(q) ||
                s.province.toLowerCase().includes(q)
            );
            renderList(filtered);
        }}

        async function openSite(id) {{
            const site = sites.find(s => s.site_id === id);
            document.getElementById('detail-modal').classList.add('active');
            document.getElementById('detail-title').innerText = site.site_name;
            document.getElementById('loading').style.display = 'block';
            
            document.getElementById('detail-stats').innerHTML = `
                <div style="background:#f8f9fa; padding:10px; border-radius:8px"><b>Array:</b> ${{site.array_size}} kWp</div>
                <div style="background:#f8f9fa; padding:10px; border-radius:8px"><b>Yield:</b> ${{site.avg_yield.toFixed(2)}}</div>
                <div style="background:#f8f9fa; padding:10px; border-radius:8px"><b>Panel:</b> ${{site.panel}}</div>
                <div style="background:#f8f9fa; padding:10px; border-radius:8px"><b>Project:</b> ${{site.project}}</div>
            `;

            if(chartInstance) chartInstance.destroy();

            // Fetch History
            const res = await fetch(`site_data/${{id}}.json`);
            const data = await res.json();
            document.getElementById('loading').style.display = 'none';

            // Chart
            const ctx = document.getElementById('chart').getContext('2d');
            const recent = data.history.slice(-30); // Last 30 days
            
            chartInstance = new Chart(ctx, {{
                type: 'bar',
                data: {{
                    labels: recent.map(d => d.date.substring(5)),
                    datasets: [{{
                        label: 'Production (kWh)',
                        data: recent.map(d => d.kwh),
                        backgroundColor: '#3498db'
                    }}]
                }},
                options: {{ responsive: true, maintainAspectRatio: false }}
            }});
        }}

        function closeModal() {{
            document.getElementById('detail-modal').classList.remove('active');
        }}

        renderList(sites);
    </script>
</body>
</html>"""

    with open(output_dir / "index.html", "w", encoding="utf-8") as f:
        f.write(html_content)
    
    print(f"✓ Mobile site generated at: {output_dir}")

if __name__ == "__main__":
    generate_mobile_site()
